"""create investment table

Revision ID: 37013825f347
Revises: 
Create Date: 2021-07-15 00:15:20.737035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37013825f347'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investment',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('application', sa.String(length=200), nullable=True),
    sa.Column('mandatory_business', sa.BigInteger(), nullable=True),
    sa.Column('investment_value', sa.BigInteger(), nullable=True),
    sa.Column('return_on_investment', sa.BigInteger(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('investment')
    # ### end Alembic commands ###
